In [13]:
# Matrix Multiplication (with a Vector)
import numpy as np
import torch
import tensorflow as tf

In [14]:
A = np.array([[3,4],[5,6],[7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [15]:
b = np.array([1,2])
b

array([1, 2])

In [16]:
np.dot(A,b) # Even though technically dot products are between  vectors only 

array([11, 17, 23])

In [17]:
A_pt = torch.tensor([[3,4],[5,6],[7,8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [18]:

b_pt = torch.tensor([1,2])
b_pt

tensor([1, 2])

In [19]:
torch.matmul(A_pt,b_pt) # like np.dot(), automatically infers dimensions in order to perform dot product, matvec, or matrix multiplication

tensor([11, 17, 23])

In [20]:
A_tf = tf.Variable([[3,4],[5,6],[7,8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]])>

In [21]:
b_tf = tf.Variable([1,2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [22]:
tf.linalg.matvec(A_tf,b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

In [23]:
# (Matrix-by-) Matrix multiplication
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [24]:
B = np.array([[1,9],[2,0]])
B

array([[1, 9],
       [2, 0]])

In [25]:
np.dot(A,B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [27]:
# Note that matrix multiplication is not "commutative" (i.e. A != B) 
# np.dot(B,A)

In [38]:
B_pt = torch.tensor([[1,9],[2,0]])
B_pt

tensor([[1, 9],
        [2, 0]])

In [39]:
torch.matmul(A_pt,B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [30]:
B_tf = tf.Variable([[1,9],[2,0]])
B_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 9],
       [2, 0]])>

In [40]:
tf.matmul(A_tf,B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]])>