2x2 Matrix Determinants

In [3]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [5]:
np.linalg.det(X)

-2.0000000000000013

In [6]:
N = np.array([[-4,1],[-8,2]])
N

array([[-4,  1],
       [-8,  2]])

In [7]:
np.linalg.det(N)

0.0

In [10]:
# Uncommenting the following line results in a "singular matrix" error
# np.linalg.inv(N)

In [18]:
N = torch.tensor([[-4,1],[-8,2.]])
N

tensor([[-4.,  1.],
        [-8.,  2.]])

In [20]:
torch.det(N)

tensor(-0.)

Generalizing Determinants 

In [21]:
X = np.array([[1,2,4],[2,-1,3],[0,5,1]])
X

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

In [22]:
np.linalg.det(X)

19.999999999999996