Eigendecomposition

In [1]:
import numpy as np

In [2]:
A = np.array([[4,2],[-5,-3]])
A

array([[ 4,  2],
       [-5, -3]])

In [5]:
lamdas, V = np.linalg.eig(A)

In [6]:
V

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [7]:
Vinv = np.linalg.inv(V)
Vinv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [8]:
Lambda = np.diag(lamdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [9]:
np.dot(V, np.dot(Lambda,Vinv))

array([[ 4.,  2.],
       [-5., -3.]])

In [10]:
A = np.array([[2,1],[1,2]])
A

array([[2, 1],
       [1, 2]])

In [11]:
lamdas, Q = np.linalg.eig(A)

In [12]:
lamdas

array([3., 1.])

In [14]:
Lambda = np.diag(lamdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [15]:
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [16]:
np.dot(Q, np.dot(Lambda,Q.T))

array([[2., 1.],
       [1., 2.]])

Exercises

In [17]:
import torch

In [18]:
P = torch.tensor([[25,2,-5],[3,-2,1],[5,7,4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [20]:
lamdas, V = torch.linalg.eig(P)

In [21]:
V

tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])

In [22]:
lamdas

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [23]:
Vinv = torch.linalg.inv(V)

In [24]:
Lambda = torch.diag(lamdas)
Lambda

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [26]:
np.dot(V, np.dot(Lambda,Vinv))

array([[24.999989 +0.j,  1.9999988+0.j, -4.999999 +0.j],
       [ 2.9999988+0.j, -1.9999999+0.j,  1.0000006+0.j],
       [ 4.9999976+0.j,  6.999998 +0.j,  4.0000005+0.j]], dtype=complex64)

In [27]:
S = torch.tensor([[25,2,-5],[2,-2,1],[-5,1,4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [33]:
lambdas , Q = torch.linalg.eig(S)

In [34]:
lamdas

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [38]:
Q

tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
        [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
        [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]])

In [41]:
Lambda = torch.diag(lambdas)
Lambda

tensor([[26.2361+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  3.2435+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -2.4796+0.j]])

In [42]:
np.dot(Q, np.dot(Lambda,Q.T))

array([[24.999992 +0.j,  1.9999996+0.j, -4.999998 +0.j],
       [ 1.9999996+0.j, -2.0000002+0.j,  0.9999999+0.j],
       [-4.9999986+0.j,  0.9999999+0.j,  3.9999995+0.j]], dtype=complex64)