In [28]:
# Symmetric Matrices

In [29]:
import numpy as np
import torch
import tensorflow as tf

In [30]:
X_sym  = np.array([[0,1,2],[1,7,8],[2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [31]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [32]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [34]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [35]:
torch.matmul(I,x_pt)

tensor([25,  2,  5])