In [1]:
# Matirx Inversion

In [3]:
import numpy as np
import tensorflow as tf
import torch

In [4]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [5]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [6]:
y = np.array([4,-7])
y

array([ 4, -7])

In [9]:
w = np.dot(Xinv,y)
w

array([-1.,  4.])

In [10]:
# show that y = Xw

In [11]:
np.dot(X,w)

array([ 4., -7.])

In [12]:
# Matrix inversion where No Solution
x = np.array([[-4,-1],[-8,-2]])
x

array([[-4, -1],
       [-8, -2]])

In [14]:
# Uncommenting the following line results in singular matrix error
# xinv = np.linalg.inv(x)