Let's calculate the psuedoinverse A^+ of some matrix A using the formula from the slides:
*A^+ = VD^+U^T*

In [2]:
import numpy as np

In [3]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [4]:
U, d, VT = np.linalg.svd(A)

In [5]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [6]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [7]:
d

array([8.66918448, 4.10429538])

To create *D^+*, we first invert the non-zero values of *d*:

In [8]:
D = np.diag(d)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [9]:
1/8.669

0.11535355865728457

In [10]:
1/4.104

0.24366471734892786

.. and then we would take the tranpose of the resulting matrix.
Because D is a diagonal matrix, this can, however, be done in a single step by inverting *D*:

In [11]:
Dinv = np.linalg.inv(D)
Dinv

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

*D^+* must have the same dimensions as *A^T* in order for *VD^+U^T* matrix multiplication to be possible:

In [12]:
Dplus = np.concatenate((Dinv, np.array([[0,0]]).T),axis=1)
Dplus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

In [13]:
np.dot(VT.T, np.dot(Dplus,U.T))

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

Working out this derivation is helpful for understanding how Moore-Penrose psuedoinverse work, but unsuprisingly NumPy is loaded with an existing method pinv()

In [14]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])