In [1]:
# Tensor Transposition 
import numpy as np

In [3]:
x = np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
x.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [7]:
import tensorflow as tf
import torch

In [8]:
x_tf = tf.Variable([[25,2],[5,26],[3,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [9]:
tf.transpose(x_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

In [12]:
x_pt = torch.tensor([[25,2],[5,26],[3,7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [13]:
x_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [14]:
# Basic Tensor Arithmetic 
# Adding or multiplying with scalar applies operation to all elements and tensor shape is retained 

x*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [16]:
x+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [15]:
x*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [17]:
x_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [18]:
torch.add(torch.mul(x_pt,2),2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [19]:
x_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [20]:
tf.add(tf.multiply(x_tf,2),2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [22]:
'''
If two tensors have the same size, operations are often by default applied element-wise. This is not matrix multiplication, 
but is rather called the Hadamard product or simply the element-wise product.
'''

'\nIf two tensors have the same size, operations are often by default applied element-wise. This is not matrix multiplication, \nbut is rather called the Hadamard product or simply the element-wise product.\n'

In [24]:
A = x+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [25]:
A + x

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [27]:
# Hadamard product
A * x

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [29]:
A_pt = x_pt + 2
A_pt

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [30]:
A_pt + x_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [31]:
A_pt * x_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [32]:
A_tf = x_tf + 2
A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[27,  4],
       [ 7, 28],
       [ 5,  9]])>

In [33]:
A_tf + x_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [35]:
A_tf * x_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]])>

In [36]:
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [37]:
x.sum()

68

In [38]:
torch.sum(x_pt)

tensor(68)

In [39]:
tf.reduce_sum(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [40]:
# Can also be done along one specific axis alone eg:
x.sum(axis=0)

array([33, 35])

In [41]:
x.sum(axis=1)

array([27, 31, 10])

In [42]:
torch.sum(x_pt,0)

tensor([33, 35])

In [44]:
tf.reduce_sum(x_tf,1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10])>