In [16]:
import numpy as np
import tensorflow as tf
import torch

In [17]:
x = np.array([25,2,5])
x


array([25,  2,  5])

In [18]:

x_tf = tf.Variable([25,2,5])
x_tf


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [19]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [20]:
y = np.array([0,1,2])
y

array([0, 1, 2])

In [21]:
y_tf = tf.Variable([0,1,2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2])>

In [22]:
y_pt = torch.tensor([0,1,2])
y_pt

tensor([0, 1, 2])

In [23]:
np.dot(x,y)

12

In [25]:
np.dot(x_pt,y_pt)

12

In [26]:
torch.dot(torch.tensor([25,2,5.]),torch.tensor([0,1,2.]))

tensor(12.)

In [27]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=12>