In [14]:
# What is the tranaspose of this vector:
'''
[25]
[2]
[-3]
[-23]
'''

import numpy as np

In [15]:
x = np.array([[25],[2],[-3],[-23]])
x

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [16]:
x.shape

(4, 1)

In [17]:
x.T

array([[ 25,   2,  -3, -23]])

In [18]:
# Using algebric notation, what are the dimnesions of this matrix Y
'''
y = [42   4   7  99  ]
    [-99 -3   17  22 ]
'''
y = np.array([[42,4,7,9,],[-99,-3,17,22]])
y 

array([[ 42,   4,   7,   9],
       [-99,  -3,  17,  22]])

In [19]:
y.shape

(2, 4)