In [14]:
import numpy as np

In [15]:
y = np.array([[42,4,7,99],[-99,-3,17,22]])
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [16]:
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [17]:
# Hadamard Prodcut
a = np.array([[25,10],[-2,1]])
a

array([[25, 10],
       [-2,  1]])

In [18]:
b = np.array([[-1,7],[10,8]])
b

array([[-1,  7],
       [10,  8]])

In [19]:
a * b

array([[-25,  70],
       [-20,   8]])

In [20]:
w = np.array([-1,2,-2])
w

array([-1,  2, -2])

In [21]:
x = np.array([5,10,0])
x

array([ 5, 10,  0])

In [22]:
np.dot(w,x)

15