In [11]:
# The Frobenius norm
import numpy as np
import torch
import tensorflow as tf

In [4]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [6]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [9]:
np.linalg.norm(X) # same function as for vector L2 norm

5.477225575051661

In [13]:
X_pt = torch.tensor([[1,2],[3,4.]]) # torch.norm() requires float type
X_pt

tensor([[1., 2.],
        [3., 4.]])

In [14]:
torch.norm(X_pt)

tensor(5.4772)

In [17]:
X_tf = tf.Variable([[1,2],[3,4.]]) # tf.norm() also requires float type
X_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [18]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>