In [19]:
# Matrices (Rank 2 Tensors) in NumPy
# Use array () with nestes brackets:
import numpy as np

In [20]:
x = np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [21]:
x.shape

(3, 2)

In [22]:
x.size

6

In [23]:
# Select left column of matrix (zero-indexed)
x[:,0]

array([25,  5,  3])

In [24]:
# Select middle row of matrix
x[1,:]

array([ 5, 26])

In [25]:
# Another slicing-by-index example
x[0:2,0:2]

array([[25,  2],
       [ 5, 26]])

In [26]:
# Matrices in Pytorch
import torch

In [27]:
x_pt = torch.tensor([[25,2],[5,26],[3,7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [28]:
x_pt.shape

torch.Size([3, 2])

In [29]:
x_pt[1,:]

tensor([ 5, 26])

In [30]:
# Matrices in TensorFlow
import tensorflow as tf

In [31]:
x_tf = tf.Variable([[25,2],[5,26],[3,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [32]:
tf.rank(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [33]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [34]:
x_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>