A = UDV^T

Where:

*U* is an orthogonal *m* x *m* matrix; its columns are the left-singular vectors of *A*

*V* is an orthogonal *n* x *n* matrix; its columns are the right-singular vectors of *A*

*D* is a diagonal *m* x *n* matrix; elements along its diagonal are the singular values of *A* 

In [2]:
import numpy as np

In [3]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [5]:
U, d, VT = np.linalg.svd(A) # V is already transposed

In [6]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [7]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [8]:
d

array([8.66918448, 4.10429538])

In [9]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

*D* must have same dimensions as *A* for *UDV^T* matrix multiplication to be possible

In [10]:
D = np.concatenate((np.diag(d),[[0,0]]),axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [11]:
np.dot(U, np.dot(D,VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

SVD and eigendecomposition are closely related to each other:

Left-singular vectors of *A* = eigenvectors of *AA^T*

Right-singular vectors of *A* = eigenvectors of *A^TA*

Non-zero singular values of *A* = square roots of eigenvalues of *AA^T* = square roots of eigenvalues of *A^TA*