In [49]:
# Vectors (Rank 1 Tensors) in NumPy 
import numpy as np

In [50]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [51]:
len(x)

3

In [52]:
x.shape

(3,)

In [53]:
type(x)

numpy.ndarray

In [54]:
x[0] # Zero-indexed

25

In [55]:
type(x[0])

numpy.int32

In [56]:
# Vector Transposition
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([25,  2,  5])

In [57]:
x_t.shape

(3,)

In [58]:
# ... but it does if we used nested "matrix-style" brackets:
y = np.array([[25,2,5]])
y 

array([[25,  2,  5]])

In [59]:
y.shape

(1, 3)

In [60]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [61]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [62]:
# Zero vectors 
# have no effect if added to another vector 
z = np.zeros(3)
z

array([0., 0., 0.])

In [63]:
# Vectors in Pytorch and tensorflow
import torch
import tensorflow as tf

In [64]:
x_pt = torch.tensor([25,2,3])
x_pt

tensor([25,  2,  3])

In [65]:
x_tf = tf.Variable([25,2,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  3])>

In [66]:
# L^2 Norm (L2 Norm)
x

array([25,  2,  5])

In [67]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [68]:
np.linalg.norm(x)
# So if units in this 3-dimensional vector space are meters, then the vector x has length of 25.6m

25.573423705088842

In [69]:
# L^1 Norm (L1 Norm)
x

array([25,  2,  5])

In [70]:
np.abs(25) + np.abs(2) + np.abs(5)

32

In [71]:
# Squared L^2 Norm (Sqaured L2 Norm)
x

array([25,  2,  5])

In [72]:
(25**2 + 2**2 + 5**2)

654

In [73]:
# Sqaured L2 Norm equals simply xTx (x-Transpose * x)
np.dot(x,x)

654

In [74]:
# Max Norm
x

array([25,  2,  5])

In [75]:
np.max([np.abs(25),np.abs(2),np.abs(5)])

25